# Generated by Django 4.2.11 on 2024-04-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notelists',
            name='color',
        ),
    ]
