# Generated by Django 4.2.11 on 2024-04-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notelists_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelists',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
