# Generated by Django 5.0.4 on 2024-04-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasks',
            name='owner',
        ),
    ]
