# Generated by Django 4.2.11 on 2024-04-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_subtasks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklists',
            name='color',
        ),
    ]
