# Generated by Django 4.2.11 on 2024-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tasklists_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklists',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
